[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
exclude = [
    "visualization/",
    "utils/jit_ops.py"
]

[tool.flake8]
max-line-length = 120
extend-ignore = "E203,W503"
per-file-ignores = "**/__init__.py:F401"
